
// BusinessBuilder

export const ADD_BUSINESS = 'ADD_BUSINESS'; 
export const SWITCH_BUSINESS_TAB = 'SWITCH_BUSINESS_TAB'; 
export const ADD_WORKING_HOURS = 'ADD_WORKING_HOURS'; 

export const FETCH_BUSINESSDATA_BEGIN   = 'FETCH_BUSINESSDATA_BEGIN'; 
export const FETCH_BUSINESSDATA_SUCCESS = 'FETCH_BUSINESSDATA_SUCCESS';
export const FETCH_BUSINESSDATA_FAILURE = 'FETCH_BUSINESSDATA_FAILURE';

export const CLEAR_BUSINESS_BUILDER_STATE = 'CLEAR_BUSINESS_BUILDER_STATE';
export const DELETE_BUSINESS = 'DELETE_BUSINESS';

export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const UPDATE_DATA = 'UPDATE_DATA';

// STOPWATCHES

export const ADD_STOPWATCH = 'ADD_STOPWATCH';
export const DELETE_STOPWATCH = 'DELETE_STOPWATCH';

export const INITIALIZE_STOPWATCHES_START = 'INITIALIZE_STOPWATCHES_START'; 
export const INITIALIZE_STOPWATCHES_SUCCESS = 'INITIALIZE_STOPWATCHES_SUCCESS'; 

export const SAVE_CURRENT_STOPWATCH_TIME = 'SAVE_CURRENT_STOPWATCH_TIME'; 
export const CLEAR_CURRENT_STOPWATCH_TIME = 'CLEAR_CURRENT_STOPWATCH_TIME'; 
export const SAVE_TIMER_TIME = 'SAVE_TIMER_TIME'; 
export const UPDATE_STOPWATCH = 'UPDATE_STOPWATCH';
export const CLEAR_STOPWATCH = 'CLEAR_STOPWATCH'; 
export const CLEAR_STOPWATCH_STATE = 'CLEAR_STOPWATCH_STATE'; 
export const STOP_ALL_TIMERS = 'STOP_ALL_TIMERS'; 


// Auth

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CLEAR_ERROR = 'CLEAR_ERROR';

// siteOptions

export const TOGGLE_SIDEBAR_MENU = 'TOGGLE_SIDEBAR_MENU';
export const DEFAULT_SIDEBAR_MENU_STATE = 'DEFAULT_SIDEBAR_MENU_STATE';

// Temporarily not used

export const CLEAR_CURRENT_COUNTDOWN_TIME = 'CLEAR_CURRENT_COUNTDOWN_TIME';
export const STOPWATCH_OR_COUNTDOWN_IS_SHOWN_HANDLER = 'STOPWATCH_OR_COUNTDOWN_IS_SHOWN_HANDLER';
export const SAVE_CURRENT_MINI_STOPWATCH_TIME = 'SAVE_CURRENT_MINI_STOPWATCH_TIME';
export const INCREASE_TIMER = 'INCREASE_TIMER';
export const SAVE_TIMER_ID = 'SAVE_TIMER_ID';
